#!/bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root."
    exit 1
fi
if [ -z "$1" ]; then
    echo "Usage: sudo bash Aurora /path/to/rawshim.bin /path/to/payload/dir/"
    exit 1
fi

temproot=$(mktemp -d)
loopdev=$(losetup -Pf --show $shim)
mount -o ro "${loopdev}p3" "$temproot"

export arch=x86_64
if [ -f "$temproot/bin/bash" ]; then
    case "$(file -b "$temproot/bin/bash" | awk -F ', ' '{print $2}' | tr '[:upper:]' '[:lower:]')" in
        *aarch64* | *armv8* | *arm*) export arch=aarch64 ;;
    esac
fi

umount "$temproot"
losetup -d $loopdev
rmdir "$temproot"