#!/bootstrap/busybox sh

STATEFUL_MNT=/stateful_init

fail() {
	printf "%b\nAborting.\n" "$*" >&2
	cleanup || :
	tail -f /dev/null
	exit 1
}

cleanup() {
	umount "$STATEFUL_MNT" || :
}

trap 'fail "An unhandled error occured."' ERR

# ensure stdin works
exec </proc/self/fd/1

LSB_FACTORY=/etc/lsb-factory
export PATH=/bootstrap
busybox --install /bootstrap

[ -f "$LSB_FACTORY" ] || fail "Could not find lsb-factory file."
. "$LSB_FACTORY"
[ -b "$STATEFUL_DEV" ] || fail "Could not determine stateful partition of USB device."

mkdir -p "$STATEFUL_MNT"
umount "$STATEFUL_DEV"
mount "$STATEFUL_DEV" "$STATEFUL_MNT" || fail "Failed to mount $STATEFUL_DEV"

rm -rf /init || :
INIT_SRC="$STATEFUL_MNT"/init
cp "$INIT_SRC" /init
exec /init "$STATEFUL_MNT" "$STATEFUL_DEV" "$REAL_USB_DEV" || :
fail "Failed to exec init script."
