#!/bin/busybox sh

# replace /dev/sda4 with actual root-b
mkdir -p /newroot
cgpt find -l ROOT-A "$dev" || cgpt find -t rootfs "$dev" | head -n 1
mount /dev/sda4 /newroot
mkdir -p /newroot/tmp/oldroot
pivot_root /newroot /newroot/tmp/oldroot
ls -lah /sbin/init
chmod +x /sbin/init
exec /sbin/init
