#!/bin/busybox sh

echo "Making the newroot partition..."
mkdir -p /newroot || sleep 10
sleep 1
dev_partition=$(blkid | grep 'LABEL="Aurora"' | awk -F: '{print $1}' || true)
if [ -z "$dev_partition" ]; then
    echo "failed to find aurora partition"
    exit 1
fi
export tty="/dev/tty"
[ -e /dev/pts/0 ] && export tty="/dev/pts/0"
chmod +x /.UNRESIZED
bash /.UNRESIZED
chmod +x /.SHIMBOOT
bash /.SHIMBOOT <${tty} >>${tty}
rm -f /.SHIMBOOT
sleep 2
dev=$(echo "$dev_partition" | sed -E 's/p?[0-9]+$//')

echo "Mounting device..."
mount $dev_partition /newroot || mount /dev/sda4 /newroot || mount /dev/mmcblk1p4 /newroot # incase of thuggery from dev_partition

echo "Moving mounts to /newroot"
mkdir -p "/newroot/sys"
mount -n -o move "/sys" "/newroot/sys"
mkdir -p "/newroot/proc"
mount -n -o move "/proc" "/newroot/proc"
mkdir -p "/newroot/dev"
mount -n -o move "/dev" "/newroot/dev"
mkdir -p "/newroot/run"
mount -n -o move "/run" "/newroot/run"

echo "exec switch_root"
echo "this shouldn't take more than a few seconds"
chmod +x /newroot/sbin/init
exec switch_root /newroot /sbin/init -v --default-console output || :