#!/bin/busybox sh

echo "Making the newroot partition..."
mkdir -p /newroot
if [ -f "/.UNRESIZED" ]; then
    echo "Resizing rootfs..."
    /sbin/resizedafiles
fi
dev_partition=$(blkid | grep 'LABEL="Aurora"' | awk -F: '{print $1}' || true)
if [ -z "$dev_partition" ]; then
    echo "failed to find aurora partition"
    exit 10
fi

dev=$(echo "$dev_partition" | sed -E 's/p?[0-9]+$//')

echo "Mounting device..."
mount $dev_partition /newroot || mount /dev/sda4 /newroot || mount /dev/mmcblk1p4 /newroot # incase of thuggery from dev_partition

echo "Moving mounts to /newroot"
mkdir -p "/newroot/sys"
mount -n -o move "/sys" "/newroot/sys"
mkdir -p "/newroot/proc"
mount -n -o move "/proc" "/newroot/proc"
mkdir -p "/newroot/dev"
mount -n -o move "/dev" "/newroot/dev"
mkdir -p "/newroot/run"
mount -n -o move "/run" "/newroot/run"

echo "exec switch_root"
echo "this shouldn't take more than a few seconds"
chmod +x /newroot/sbin/init
exec switch_root /newroot /sbin/init -v --default-console output || :