#!/bin/bash

cd /
source /usr/share/aurora/centering
tar xzf nothingbeatsajet2holiday.tar.gz

for frame in $(ls nothingbeatsajet2holiday/frame_*.txt | sort); do
    clear
    cat "$frame" | center
    sleep 0.04
done

rm -rf /nothingbeatsajet2holiday