#!/bin/bash

source /usr/share/aurora/functions
cd /

canwifi apk add mpv yt-dlp
(
    killall frecon-lite
    mpv --vo=drm --loop --volume=100 https://www.youtube.com/watch?v=YQZEoZ4W0ac --slang=en --ytdl-raw-options='ignore-config=,sub-langs="^en.*",write-subs=,write-auto-subs=
)