#!/bin/bash

source /usr/share/aurora/functions
cd /

canwifi || return

apk add mpv
wget -q --show-progress https://raw.githubusercontent.com/EtherealWorkshop/Aurora/refs/heads/alpine/jet2holiday.mp4
(
    killall frecon-lite
    mpv --vo=drm --loop /jet2holiday.mp4 --volume=100
)