#!/bin/bash

source /usr/share/aurora/functions
cd /
if [ ! -n "$rogged" ]; then rogged=$((RANDOM % 100)); fi
if [ "$rogged" -eq 69 ]; then
    (
        killall frecon-lite
        mpv --vo=drm --loop /.jeff2holiday.mp4 --volume=100
    )
else
    (
        killall frecon-lite
        mpv --vo=drm --loop /jet2holiday.mp4 --volume=100
    )
fi