#!/bin/bash

mkdir -p "/tmp/apk-tools-static"
wget -q --show-progress "https://dl-cdn.alpinelinux.org/alpine/latest-stable/main/x86_64/$(echo "$(wget -qO- --show-progress "https://dl-cdn.alpinelinux.org/alpine/latest-stable/main/x86_64/" | grep "apk-tools-static")" | pcregrep -o1 '"(.+?.apk)"')" -O "/tmp/apk-tools-static/pkg.apk"
tar --warning=no-unknown-keyword -xzf "/tmp/apk-tools-static/pkg.apk" -C "/tmp/apk-tools-static"
chmod +x /tmp/apk-tools-static/sbin/apk.static

/tmp/apk-tools-static/sbin/apk.static --arch x86_64 -X http://dl-cdn.alpinelinux.org/alpine/edge/main/ -U --allow-untrusted --root "/" --initdb add alpine-base