#!/bin/bash

echo -e "${MAGENTA_B}Credits"
echo -e "${PINK_B}Sophia${COLOR_RESET}: Lead developer of Aurora, Got Wifi"
echo -e "${RED_B}Mariah Carey${COLOR_RESET}: Bugfixing and bugtesting"
echo -e "${GEEN_B}xmb9${COLOR_RESET}: Made Priism, Giving Aurora the ability to Boot Shims & Use Reco Images"
echo -e "${YELLOW_B}Synaptic${COLOR_RESET}: Emotional Support"
echo -e "${CYAN_B}Simon${COLOR_RESET}: Brainstormed how to do wifi, helped with dhcpcd"
echo -e "${BLUE_B}kraeb${COLOR_RESET}: QoL improvements and initial idea"
echo -e "${MAGNETA_B}AC3${COLOR_RESET}: Literally nothing"
echo -e "${GEEN_B}Rainestorme${COLOR_RESET}: Murkmod's version finder"
echo -e "${RED_B}kxtz:${COLOR_RESET} KVS"
echo -e " "
read -p "Press Enter to return to the main menu..."
