#!/bin/bash

dev_partition=$(blkid | grep 'LABEL="Aurora"' | awk -F: '{print $1}')
dev=$(echo "$dev_partition" | sed -E 's/p?[0-9]+$//')

parted -fs $dev align-check opt 4
growpart $dev 4
e2fsck -fy $dev_partition
resize2fs -p $dev_partition