#!/bin/sh

printf "\033]input:on\a"
printf "\033[?25h"

/bin/busybox --install -s /bin

rm -f /init
clear

export TTY1="/dev/tty1"
export TTY2="/dev/tty2"
export TTY3="/dev/tty4"
[ -e /dev/pts/0 ] && export TTY1="/dev/pts/0" && export TTY2="/dev/pts/1" && export TTY3="/dev/pts/3"

setsid -c test
hostname aurora
export needswifi=1
exec <${TTY1} >>${TTY1} 2>&1
exec bash -l /usr/share/aurora/aurora.sh <${TTY1} >>${TTY1} 2>&1