#!/bin/sh

DEBUG="$1"
set -e
if [ "$DEBUG" ]; then
  set -x
fi

setup-hostname Aurora
setup-apkrepos "http://dl-cdn.alpinelinux.org/alpine/v3.21/main/" "http://dl-cdn.alpinelinux.org/alpine/v3.21/community/"

rc-update add acpid default
rc-update add bootmisc boot
rc-update add crond default
rc-update add devfs sysinit
rc-update add sysfs sysinit
rc-update add dmesg sysinit
rc-update add hostname boot
rc-update add hwclock boot
rc-update add hwdrivers sysinit
rc-update add killprocs shutdown
rc-update add mdev sysinit
rc-update add modules boot
rc-update add mount-ro shutdown
rc-update add networking boot
rc-update add savecache shutdown
rc-update add seedrng boot
rc-update add swap boot
rc-update add syslog boot

echo "#!/sbin/openrc-run
command='/usr/bin/killall frecon-lite'
" > /etc/init.d/killfrecon
chmod +x /etc/init.d/killfrecon
rc-update add killfrecon boot

modules="$(ls /etc/modules-load.d)"
for module in $modules; do
  cat "/etc/modules-load.d/$module" >> /etc/modules
  echo >> /etc/modules
done

apk add elogind polkit-elogind udisks2 polkit-elogind sudo zram-init iwd dhcpcd network-manager-applet wpa_supplicant adw-gtk3 cloud-utils-growpart nano mousepad

rc-update add iwd default
rc-update add wpa_supplicant default
rc-update add zram-init default
rc-update add elogind default
rc-update add dbus default

sed -i 's/=zstd/=lzo/' /etc/conf.d/zram-init
sed -i '/size0=512/d' /etc/conf.d/zram-init
sed -i '/blk1=1024/d' /etc/conf.d/zram-init
echo "size0=\`LC_ALL=C free -m | awk '/^Mem:/{print int(\$2/2)}'\`" >> /etc/conf.d/zram-init

set_password root root
